/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadCliente.java
 *
 * Created on 05/09/2010, 15:43:53
 */

package banco.cliente;

import java.io.EOFException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import banco.cliente.deprecated.Login;
/**
 *
 * @author usuariio
 */
public class CadCliente extends javax.swing.JFrame {

    /** Creates new form CadCliente */
    public CadCliente() {
        initComponents();
        int conta = 100000 + (int)(Math.random() *999999);
        tfConta.setText(Integer.toString(conta));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNome = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        lbDtNascimento = new javax.swing.JLabel();
        lbConta = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfCpf = new javax.swing.JTextField();
        tfDtNascimento = new javax.swing.JTextField();
        tfConta = new javax.swing.JTextField();
        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tfRG = new javax.swing.JTextField();
        lbRG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setResizable(false);

        lbNome.setText("Nome: ");

        lbCpf.setText("CPF: ");

        lbDtNascimento.setText("Data de nascimento: ");

        lbConta.setText("Nº da Conta: ");

        tfConta.setBackground(new java.awt.Color(157, 151, 146));
        tfConta.setEditable(false);

        lbLogin.setText("Login: ");

        lbSenha.setText("Senha: ");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lbRG.setText("RG: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConta)
                    .addComponent(lbDtNascimento)
                    .addComponent(lbLogin)
                    .addComponent(lbSenha)
                    .addComponent(lbNome)
                    .addComponent(lbCpf)
                    .addComponent(lbRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRG, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(tfDtNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(tfConta, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(tfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(pfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(tfCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addContainerGap(163, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDtNascimento)
                    .addComponent(tfDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConta)
                    .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnCadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTfRG() {
        return tfRG;
    }

    public void setTfRG(JTextField tfRG) {
        this.tfRG = tfRG;
    }

    public JTextField getTfConta() {
        return tfConta;
    }

    public void setTfConta(JTextField tfConta) {
        this.tfConta = tfConta;
    }

    public JTextField getTfCpf() {
        return tfCpf;
    }

    public void setTfCpf(JTextField tfCpf) {
        this.tfCpf = tfCpf;
    }

    public JTextField getTfLogin() {
        return tfLogin;
    }

    public void setTfLogin(JTextField tfLogin) {
        this.tfLogin = tfLogin;
    }

    public JTextField getTfNome() {
        return tfNome;
    }

    public void setTfNome(JTextField tfNome) {
        this.tfNome = tfNome;
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String Nome = tfNome.getText(); 
        String Cpf = tfCpf.getText();
        String RG = tfRG.getText();
        String DtNasc = tfDtNascimento.getText();
        String Conta = tfConta.getText();
        String Login = tfLogin.getText();
        String Senha = this.pfSenha.getText();
        String msg = "2 "+Nome+" "+Cpf+" "+RG+" "+DtNasc+" "+Conta+" "+Login+" "+Senha;
        String resposta = "";
        Socket socket = null;
        int servidor = 1 + (int)(Math.random() *3);
        System.out.println(servidor);
        boolean valida = true;

        if(Nome.equals("")||Nome.equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo Nome em branco.", "Erro!", JOptionPane.OK_OPTION);
            valida = false;
        }
        if(Cpf.equals("")||Cpf.equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo CPF em branco.", "Erro!", JOptionPane.OK_OPTION);
            valida = false;
        }
        if(RG.equals("")||RG.equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo RG em branco.", "Erro!", JOptionPane.OK_OPTION);
            valida = false;
        }
        if(DtNasc.equals("")||DtNasc.equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo Data de nascimento em branco.", "Erro!", JOptionPane.OK_OPTION);
            valida = false;
        }
        if(Conta.equals("")||Conta.equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo Nº da Conta em branco.", "Erro!", JOptionPane.OK_OPTION);
            valida = false;
        }
        if(Login.equals("")||Login.equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo Login em branco.", "Erro!", JOptionPane.OK_OPTION);
            valida = false;
        }
        if(Senha.equals("")||Senha.equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo Senha em branco.", "Erro!", JOptionPane.OK_OPTION);
            valida = false;
        }
        if(valida = true){
        try {
            //Abrindo conexão
            int serverPort = 1001;
            switch (servidor){
                case 1:{socket = new Socket(banco.cliente.deprecated.Login.servidorA.toString(), serverPort);
                        break;
                }
                case 2:{socket = new Socket(banco.cliente.deprecated.Login.servidorB.toString(), serverPort);
                        break;
                }
                case 3:{socket = new Socket(banco.cliente.deprecated.Login.servidorC.toString(), serverPort);
                        break;
                }
                default:JOptionPane.showMessageDialog(null, "Falha no servidor!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
            ObjectOutputStream saida = new ObjectOutputStream(socket.getOutputStream());
            saida.writeObject(msg);
            saida.flush();
            ObjectInputStream entrada = new ObjectInputStream(socket.getInputStream());
            entrada.read();
            resposta = entrada.toString();
            if (resposta.equals("0")){
                JOptionPane.showMessageDialog(null, "Falha ao efetuar cadastro.", "Erro!", JOptionPane.ERROR_MESSAGE);
            }else if(resposta.equals("1")){
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!", "", JOptionPane.OK_OPTION);
                dispose();
                Login login = new Login();
                login.setLocationRelativeTo(null);
                login.setVisible(true);
            }
        }catch (UnknownHostException e){
            JOptionPane.showMessageDialog(null, "Sock:"+e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            //System.out.println("Sock:"+e.getMessage());
        }catch (EOFException e){
            JOptionPane.showMessageDialog(null, "EOF:"+e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            //System.out.println("EOF:"+e.getMessage());
        }catch (IOException e){
            JOptionPane.showMessageDialog(null, "IO:"+e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            //System.out.println("IO:"+e.getMessage());
        } finally {
            if(socket!=null)
            try {
                socket.close();
            }
            catch (IOException e){
                JOptionPane.showMessageDialog(null, "Close:"+e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
                //System.out.println("close:"+e.getMessage());
            }
        }// try
      }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lbConta;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbDtNascimento;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRG;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfConta;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfDtNascimento;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfRG;
    // End of variables declaration//GEN-END:variables

}
