/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 05/09/2010, 14:55:33
 */

package banco.cliente;

import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.net.*;
import javax.swing.JOptionPane;



public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        lbcadastro = new javax.swing.JLabel();
        lbCliqueAqui = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tfSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        lbLogin.setText("Login: ");

        lbSenha.setText("Senha: ");

        tfLogin.setMaximumSize(new java.awt.Dimension(6, 6));
        tfLogin.setMinimumSize(new java.awt.Dimension(6, 6));

        lbcadastro.setText("Se não possui um cadastro ");

        lbCliqueAqui.setForeground(new java.awt.Color(0, 51, 255));
        lbCliqueAqui.setText("Clique aqui!");
        lbCliqueAqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCliqueAquiMouseClicked(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tfSenha.setMaximumSize(new java.awt.Dimension(6, 6));
        tfSenha.setMinimumSize(new java.awt.Dimension(6, 6));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogin)
                    .addComponent(lbSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbcadastro)
                        .addGap(6, 6, 6)
                        .addComponent(lbCliqueAqui))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenha)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcadastro)
                    .addComponent(lbCliqueAqui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogin)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPasswordField getTfSenha() {
        return tfSenha;
    }

    public void setTfSenha(JPasswordField tfSenha) {
        this.tfSenha = tfSenha;
    }
    public JTextField getTfLogin() {
        return tfLogin;
    }

    public void setTfLogin(JTextField tfLogin) {
        this.tfLogin = tfLogin;
    }

    //Configurar o IP Conforme os servidores
    public static String servidorA = "127.0.0.1";
    public static String servidorB = "127.0.0.1";
    public static String servidorC = "127.0.0.1";

    public static String cliConta = "";
    public static String cliNome = "";
    public static String cliSaldo = "";
    public static String cliServidor = "";


    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
         String Login = tfLogin.getText();
         String Senha = tfSenha.getText();
         String msg = "1 "+Login+" "+Senha;

         if (Login.equals("")|| Login.equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo Login em branco.", "Erro!", JOptionPane.OK_OPTION);
         }
         if (Senha.equals("")||Senha.equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo Senha em branco.", "Erro!", JOptionPane.OK_OPTION);
         }

         if ((Login.equals("admin"))&&(Senha.equals("admin"))){
            cliServidor = "Administrador";
            cliConta = "---";
            cliNome = "Administrador";
            cliSaldo = "R$ 0,00";
            dispose();
            Principal programa = new Principal();
            programa.setLocationRelativeTo(null);
            programa.setVisible(true);
         }else{
            String respostaA = "";
            String respostaB = "";
            String respostaC = "";
//            ConexaoServidor A = new CliThread();
            ConexaoServidor A = new ConexaoServidorProxy();
            respostaA = A.ComunicaServidor(msg, servidorA);
            
            ConexaoServidor B = new CliThread();
            respostaB = B.ComunicaServidor(msg, servidorB);
            
            ConexaoServidor C = new CliThread();
            respostaC = C.ComunicaServidor(msg, servidorC);

            if (!respostaA.equals("0")){
                cliServidor = servidorA.toString();
                int tam = respostaA.length();
                char palavra[]=respostaA.toCharArray();
                int cont = 2;
                int inicio = 0;
                for (int i = 1; i<=3 ;i++){
                    inicio = cont;
                    while (palavra[cont]!= ' '){
                        cont++;
                        if (cont == tam){
                            break;
                        }
                    }
                    switch(i){
                        case 1:{cliConta = respostaA.substring(inicio, cont-1);
                                cont++;
                                }
                        case 2:{cliNome = respostaA.substring(inicio, cont-1);
                                cont++;
                               }
                        case 3:{cliSaldo = respostaA.substring(inicio);
                                cont++;
                                }
                    }
                }
                dispose();
                Principal programa = new Principal();
                programa.setLocationRelativeTo(null);
                programa.setVisible(true);
            }else if (!respostaB.equals("0")){
                cliServidor = servidorB.toString();
                int tam = respostaB.length();
                char palavra[]=respostaB.toCharArray();
                int cont = 2;
                int inicio = 0;
                for (int i = 1; i<=3 ;i++){
                    inicio = cont;
                    while (palavra[cont]!= ' '){
                        cont++;
                        if (cont == tam){
                            break;
                        }
                    }
                    switch(i){
                        case 1:{cliConta = respostaB.substring(inicio, cont-1);
                                cont++;
                                }
                        case 2:{cliNome = respostaB.substring(inicio, cont-1);
                                cont++;
                               }
                        case 3:{cliSaldo = respostaB.substring(inicio);
                                cont++;
                                }
                    }
                }
                dispose();
                Principal programa = new Principal();
                programa.setLocationRelativeTo(null);
                programa.setVisible(true);
            }else if (!respostaC.equals("0")){
                cliServidor = servidorC.toString();
                int tam = respostaC.length();
                char palavra[]=respostaC.toCharArray();
                int cont = 2;
                int inicio = 0;
                for (int i = 1; i<=3 ;i++){
                    inicio = cont;
                    while (palavra[cont]!= ' '){
                        cont++;
                        if (cont == tam){
                            break;
                        }
                    }
                    switch(i){
                        case 1:{cliConta = respostaC.substring(inicio, cont-1);
                                cont++;
                                }
                        case 2:{cliNome = respostaC.substring(inicio, cont-1);
                                cont++;
                               }
                        case 3:{cliSaldo = respostaC.substring(inicio);
                                cont++;
                                }
                    }
                }
                dispose();
                Principal programa = new Principal();
                programa.setLocationRelativeTo(null);
                programa.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Usuário não cadastrado!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
          }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lbCliqueAquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCliqueAquiMouseClicked
        dispose();
        CadCliente cad = new CadCliente();
        cad.setLocationRelativeTo(null);
        cad.setVisible(true);
    }//GEN-LAST:event_lbCliqueAquiMouseClicked


    public void start(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lbCliqueAqui;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbcadastro;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables

}