/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Saque.java
 *
 * Created on 05/09/2010, 16:40:07
 */

package banco.cliente;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author usuariio
 */
public class Movimento extends javax.swing.JFrame {

    /** Creates new form Saque */
    public Movimento() {
        initComponents();
        lbNome2.setText(banco.cliente.Login.cliNome.toString());
        String mesg = "6 ";
        mesg.concat(banco.cliente.Login.cliConta);
        CliThread saldo = new CliThread();
        String retorno = saldo.ComunicaServidor(mesg, banco.cliente.Login.cliServidor.toString());
        lbSaldo2.setText(retorno);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lbMovimentacao = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        lbNome = new javax.swing.JLabel();
        lbNome2 = new javax.swing.JLabel();
        lbSaldo = new javax.swing.JLabel();
        lbSaldo2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimentações");
        setResizable(false);

        lbMovimentacao.setText("Movimenta��o: ");

        lbValor.setText("Valor: ");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Saque", "Depósito" }));

        lbNome.setText("Nome:");

        lbNome2.setText("Nome Completo");

        lbSaldo.setText("Saldo: ");

        lbSaldo2.setText("Saldo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMovimentacao)
                    .addComponent(lbSaldo)
                    .addComponent(lbValor)
                    .addComponent(lbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome2)
                    .addComponent(tfValor, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(lbSaldo2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox1, 0, 158, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnConfirmar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelar))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbNome2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSaldo)
                    .addComponent(lbSaldo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMovimentacao)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValor))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLbMovimentacao() {
        return lbMovimentacao;
    }

    public void setLbMovimentacao(JLabel lbMovimentacao) {
        this.lbMovimentacao = lbMovimentacao;
    }

    public JLabel getLbNome2() {
        return lbNome2;
    }

    public void setLbNome2(JLabel lbNome2) {
        this.lbNome2 = lbNome2;
    }

    public JLabel getLbSaldo2() {
        return lbSaldo2;
    }

    public void setLbSaldo2(JLabel lbSaldo2) {
        this.lbSaldo2 = lbSaldo2;
    }

    public JTextField getTfValor() {
        return tfValor;
    }

    public void setTfValor(JTextField tfValor) {
        this.tfValor = tfValor;
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    String msg = "";
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        boolean valida = true;
        if(tfValor.toString().equals("")||tfValor.toString().equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo Valor em branco.", "Erro!", JOptionPane.OK_OPTION);
            valida = false;
        }else {
            if (jComboBox1.getSelectedItem().equals("Saque")) {
                msg = "4 " + banco.cliente.Login.cliConta.toString() + " " + tfValor.toString();

            } else if (jComboBox1.getSelectedItem().equals("Depósito")) {
                msg = "3 " + banco.cliente.Login.cliConta.toString() + " " + tfValor.toString();
            }
            CliThread mov = new CliThread();
            String retorno = mov.ComunicaServidor(msg, banco.cliente.Login.cliServidor.toString());
            if (retorno.startsWith("0")) {
                JOptionPane.showMessageDialog(null, "Falha na operação. Tente novamente!", "Erro!", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Seu saldo atual é: " + retorno.toString(), "Operação realizada com sucesso!", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbMovimentacao;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNome2;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JLabel lbSaldo2;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables

}
