/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 05/09/2010, 15:34:11
 */

package banco.cliente;

/**
 *
 * @author usuariio
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
        if(!banco.cliente.Login.cliServidor.equals("Administrador")){
            MenuBusca.setVisible(false);
        }else {
            MenuMovimentacoes.setVisible(false);
            MenuSaldo.setVisible(false);
            MenuMovimento.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JMenuBar();
        MenuArquivo = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenuItem();
        MenuCadastro = new javax.swing.JMenu();
        MenuBusca = new javax.swing.JMenuItem();
        MenuConsulta = new javax.swing.JMenu();
        MenuSaldo = new javax.swing.JMenuItem();
        MenuConta = new javax.swing.JMenuItem();
        MenuMovimentacoes = new javax.swing.JMenu();
        MenuMovimento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MenuArquivo.setText("Arquivo");

        MenuSair.setText("Sair");
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        MenuArquivo.add(MenuSair);

        MenuPrincipal.add(MenuArquivo);

        MenuCadastro.setText("Cliente");

        MenuBusca.setText("Busca ");
        MenuBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscaActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuBusca);

        MenuPrincipal.add(MenuCadastro);

        MenuConsulta.setText("Consulta");

        MenuSaldo.setText("Saldo");
        MenuSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSaldoMouseClicked(evt);
            }
        });
        MenuSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSaldoActionPerformed(evt);
            }
        });
        MenuConsulta.add(MenuSaldo);

        MenuConta.setText("Contas");
        MenuConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuContaActionPerformed(evt);
            }
        });
        MenuConsulta.add(MenuConta);

        MenuPrincipal.add(MenuConsulta);

        MenuMovimentacoes.setText("Movimentações");
        MenuMovimentacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMovimentacoesMouseClicked(evt);
            }
        });

        MenuMovimento.setText("Saque/Depósito");
        MenuMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMovimentoActionPerformed(evt);
            }
        });
        MenuMovimentacoes.add(MenuMovimento);

        MenuPrincipal.add(MenuMovimentacoes);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSaldoMouseClicked
        
    }//GEN-LAST:event_MenuSaldoMouseClicked

    private void MenuMovimentacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMovimentacoesMouseClicked
        
    }//GEN-LAST:event_MenuMovimentacoesMouseClicked

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuSairActionPerformed

    private void MenuSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSaldoActionPerformed
        Saldo saldo = new Saldo();
        saldo.setLocationRelativeTo(null);
        saldo.setVisible(true);
    }//GEN-LAST:event_MenuSaldoActionPerformed

    private void MenuMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMovimentoActionPerformed
        Movimento mov = new Movimento();
        mov.setLocationRelativeTo(null);
        mov.setVisible(true);
    }//GEN-LAST:event_MenuMovimentoActionPerformed

    private void MenuBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscaActionPerformed
        BuscaCliente buscaCli = new BuscaCliente();
        buscaCli.setLocationRelativeTo(null);
        buscaCli.setVisible(true);
    }//GEN-LAST:event_MenuBuscaActionPerformed

    private void MenuContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContaActionPerformed
        Contas consultaConta = new Contas();
        consultaConta.setLocationRelativeTo(null);
        consultaConta.setVisible(true);
    }//GEN-LAST:event_MenuContaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuArquivo;
    private javax.swing.JMenuItem MenuBusca;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuConsulta;
    private javax.swing.JMenuItem MenuConta;
    private javax.swing.JMenu MenuMovimentacoes;
    private javax.swing.JMenuItem MenuMovimento;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem MenuSair;
    private javax.swing.JMenuItem MenuSaldo;
    // End of variables declaration//GEN-END:variables

}
