/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 05/09/2010, 15:34:11
 */

package banco.cliente;

import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author usuariio
 */
public class Principal extends JFrame {

    private JMenu MenuArquivo;
    private JMenuItem MenuBusca;
    private JMenu MenuCadastro;
    private JMenu MenuConsulta;
    private JMenuItem MenuConta;
    private JMenu MenuMovimentacoes;
    private JMenuItem MenuMovimento;
    private JMenuBar MenuPrincipal;
    private JMenuItem MenuSair;
    private JMenuItem MenuSaldo;
    
    /** Creates new form Principal */
    public Principal() {
        initComponents();
        if(!banco.cliente.deprecated.Login.cliServidor.equals("Administrador")){
            MenuBusca.setVisible(false);
        }else {
            MenuMovimentacoes.setVisible(false);
            MenuSaldo.setVisible(false);
            MenuMovimento.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        MenuPrincipal = new JMenuBar();
        MenuArquivo = new JMenu();
        MenuSair = new JMenuItem();
        MenuCadastro = new JMenu();
        MenuBusca = new JMenuItem();
        MenuConsulta = new JMenu();
        MenuSaldo = new JMenuItem();
        MenuConta = new JMenuItem();
        MenuMovimentacoes = new JMenu();
        MenuMovimento = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MenuArquivo.setText("Arquivo");

        MenuSair.setText("Sair");
        MenuSair.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        MenuArquivo.add(MenuSair);

        MenuPrincipal.add(MenuArquivo);

        MenuCadastro.setText("Cliente");

        MenuBusca.setText("Busca ");
        MenuBusca.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuBuscaActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuBusca);

        MenuPrincipal.add(MenuCadastro);

        MenuConsulta.setText("Consulta");

        MenuSaldo.setText("Saldo");
        MenuSaldo.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                menuSaldoMouseClicked(evt);
            }
        });
        MenuSaldo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuSaldoActionPerformed(evt);
            }
        });
        MenuConsulta.add(MenuSaldo);

        MenuConta.setText("Contas");
        MenuConta.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuContaActionPerformed(evt);
            }
        });
        MenuConsulta.add(MenuConta);

        MenuPrincipal.add(MenuConsulta);

        MenuMovimentacoes.setText("Movimentações");
        MenuMovimentacoes.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                menuMovimentacoesMouseClicked(evt);
            }
        });

        MenuMovimento.setText("Saque/Depósito");
        MenuMovimento.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuMovimentoActionPerformed(evt);
            }
        });
        MenuMovimentacoes.add(MenuMovimento);

        MenuPrincipal.add(MenuMovimentacoes);

        setJMenuBar(MenuPrincipal);

        configuraLayout();

        
    }// </editor-fold>//GEN-END:initComponents

	private void configuraLayout() {
		GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        
        pack();
	}

    private void menuSaldoMouseClicked(MouseEvent evt) {//GEN-FIRST:event_MenuSaldoMouseClicked
        
    }//GEN-LAST:event_MenuSaldoMouseClicked

    private void menuMovimentacoesMouseClicked(MouseEvent evt) {//GEN-FIRST:event_MenuMovimentacoesMouseClicked
        
    }//GEN-LAST:event_MenuMovimentacoesMouseClicked

    private void menuSairActionPerformed(ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuSairActionPerformed

    private void menuSaldoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_MenuSaldoActionPerformed
        SaldoView saldo = new SaldoView();
        saldo.setLocationRelativeTo(null);
        saldo.setVisible(true);
    }//GEN-LAST:event_MenuSaldoActionPerformed

    private void menuMovimentoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_MenuMovimentoActionPerformed
        Movimento mov = new Movimento();
        mov.setLocationRelativeTo(null);
        mov.setVisible(true);
    }

    private void menuBuscaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_MenuBuscaActionPerformed
        BuscaCliente buscaCli = new BuscaCliente();
        buscaCli.setLocationRelativeTo(null);
        buscaCli.setVisible(true);
    }//GEN-LAST:event_MenuBuscaActionPerformed

    private void menuContaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_MenuContaActionPerformed
        ContasView consultaConta = new ContasView();
        consultaConta.setLocationRelativeTo(null);
        consultaConta.setVisible(true);
    }//GEN-LAST:event_MenuContaActionPerformed



}
