/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscaCliente.java
 *
 * Created on 17/09/2010, 23:22:02
 */

package banco.cliente.view;

import javax.swing.JOptionPane;

import banco.cliente.util.CliThread;

/**
 *
 * @author usuariio
 */
public class BuscaClienteView extends javax.swing.JFrame {

    /** Creates new form BuscaCliente */
    public BuscaClienteView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbConta = new javax.swing.JLabel();
        tfConta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        lbNome2 = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        lbCpf2 = new javax.swing.JLabel();
        lbRg = new javax.swing.JLabel();
        lbRg2 = new javax.swing.JLabel();
        lbDtNasc = new javax.swing.JLabel();
        lbDtNasc2 = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        lbLogin2 = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        lbSenha2 = new javax.swing.JLabel();
        lbSaldo = new javax.swing.JLabel();
        lbSaldo2 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busca Cliente");
        setResizable(false);

        lbConta.setText("Nº da Conta: ");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbNome.setText("Nome: ");

        lbNome2.setText("Nome");

        lbCpf.setText("CPF: ");

        lbCpf2.setText("CPF");

        lbRg.setText("RG: ");

        lbRg2.setText("RG");

        lbDtNasc.setText("Data de nascimento:");

        lbDtNasc2.setText("Data de nascimento");

        lbLogin.setText("Login: ");

        lbLogin2.setText("Login");

        lbSenha.setText("Senha: ");

        lbSenha2.setText("Senha");

        lbSaldo.setText("Saldo: ");

        lbSaldo2.setText("Saldo");

        btnOk.setText("ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSaldo)
                            .addComponent(lbCpf)
                            .addComponent(lbRg)
                            .addComponent(lbDtNasc)
                            .addComponent(lbLogin)
                            .addComponent(lbSenha)
                            .addComponent(lbNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCpf2)
                            .addComponent(lbRg2)
                            .addComponent(lbDtNasc2)
                            .addComponent(lbLogin2)
                            .addComponent(lbSenha2)
                            .addComponent(lbSaldo2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConta)
                    .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpf)
                    .addComponent(lbCpf2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRg)
                    .addComponent(lbRg2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDtNasc)
                    .addComponent(lbDtNasc2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogin)
                    .addComponent(lbLogin2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenha)
                    .addComponent(lbSenha2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSaldo)
                    .addComponent(lbSaldo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        boolean valido = true;
        if(tfConta.toString().equals("")||tfConta.toString().equals(" ")){
            JOptionPane.showMessageDialog(null, "Campo Conta em branco.", "Erro!", JOptionPane.OK_OPTION);
            valido = false;
        }
        if (valido = true){
            String msg = "7 "+tfConta.toString();
            CliThread consulta = new CliThread();
            String retorno = consulta.comunicaServidor(msg, "Administrador");
            int tam = retorno.length();
            char palavra[]=retorno.toCharArray();
            int cont = 2;
            int inicio = 0;
            for (int i = 1; i<=7 ;i++){
                inicio = cont;
                while (palavra[cont]!= ' '){
                    cont++;
                    if (cont == tam){
                        break;
                    }
                }
                switch(i){
                    case 1:{lbNome2.setText(retorno.substring(inicio, cont-1));
                            cont++;
                           }
                    case 2:{lbCpf2.setText(retorno.substring(inicio, cont-1));
                           cont++;
                          }
                    case 3:{lbRg2.setText(retorno.substring(inicio,cont-1));
                            cont++;
                          }
                    case 4:{lbDtNasc2.setText(retorno.substring(inicio, cont-1));
                           }
                    case 5:{lbLogin2.setText(retorno.substring(inicio, cont-1));
                           }
                    case 6:{lbSenha2.setText(retorno.substring(inicio, cont-1));
                            cont++;
                           }
                    case 7:{lbSaldo2.setText(retorno.substring(inicio));}
                }
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lbConta;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbCpf2;
    private javax.swing.JLabel lbDtNasc;
    private javax.swing.JLabel lbDtNasc2;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLogin2;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNome2;
    private javax.swing.JLabel lbRg;
    private javax.swing.JLabel lbRg2;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JLabel lbSaldo2;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbSenha2;
    private javax.swing.JTextField tfConta;
    // End of variables declaration//GEN-END:variables

}
